setwd("C:/A_E_Drive/20_Course_Certification/50_Getting_N_Cleaning_Data")
library(plyr)
library(dplyr)
tel<-read.table('y_test.txt')
te<-read.table('X_test.txt')
tr<-read.table('X_train.txt')
trl<-read.table('y_train.txt')
ste<-read.table('subject_test.txt')
str<-read.table('subject_train.txt')
s<-read.table('activity_labels.txt')
vn<-read.table('features.txt')
a<-cbind(Subject=ste$V1,cbind(Activity=tel$V1,te))
b<-cbind(Subject=str$V1,cbind(Activity=trl$V1,tr))
mrge<-merge(a,b,all = TRUE)
z1<-data.frame(lapply(mrge,mean))
z2<-data.frame(lapply(mrge,sd))
z<-select(merge(z1,z2,all = TRUE),V1:V561)
row.names(z)<-c('mean','stdev')
m<-merge(mrge,s,by.x = 'Activity',by.y ='V1',all=TRUE)[,c(2,1,3:564)]
n<-m %>% mutate(Activity=V2.y) %>% select(Subject:V561)
colnames(n)[3:563]=as.character(vn$V2)
summary<-ddply(n,c('Subject','Activity'),colwise(mean))
write.table(summary,file = "C:/A_E_Drive/20_Course_Certification/50_Getting_N_Cleaning_Data/summary.txt",row.names = FALSE)